version: 2
jobs:
  build_and_deploy:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Build war file
          command: mvn clean package

      - deploy:
          name: Deploy to server
          command: |
            scp -P $SSH_PORT $CIRCLE_WORKING_DIRECTORY/target/courses.war $SSH_USER@$SSH_HOST:/home/$SSH_USER

#workflows:
#  version: 2
#
#  build_only_master:
#    jobs:
#      - build:
#          filters:
#            branches:
#              ignore: /.*/
#            tags:
#              only: /^\d+\.\d+\.\d+$/
