version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Build war file
          command: mvn clean package

  deploy:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - run:
          name: Deploy to server
          command: |
            scp -P $SSH_PORT $CIRCLE_WORKING_DIRECTORY/target/courses.war $SSH_USER@$SSH_HOST:/home/vova

workflows:
  version: 2

  build_only_master:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
